import React from 'react';
import PageButtons from "./PageButtons"
import Head from "next/head"
import Link from 'next/link';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faFacebook, faInstagram, faYoutube, faTwitter } from '@fortawesome/free-brands-svg-icons'

interface pagesType {
  [key: string]: {
    pagePath: string,
    style: string,
  }
}
const pages: pagesType = {
  "Gallery": { pagePath: "/gallery", style: "" },
  "Coaches": { pagePath: "/coaches", style: "" },
  "Schedules": { pagePath: "/schedule", style: "" },
  "Classes": { pagePath: "/classes", style: "" },
  "About": { pagePath: "/about", style: "" },
}

const selectPage = (selected: string) => {
  for (const page in pages) pages[page]!.style = ""
  if (selected) pages[selected]!.style = "bg-orange-400 pointer-events-none"
}

const displayPages = (current: string) => {
  selectPage(current)
  return Object.keys(pages).map((page, index) => {
    const style = pages[page]!.style
    return (
      <PageButtons
        key={index}
        pagePath={pages[page]!.pagePath}
        label={page}
        style={style}
        select={selectPage}
      />
    )
  })
}

interface Props {
  current: string;
}

const Header: React.FC<Props> = (props) => {
  return (
    <>
      <Head>
        <title>Velocity Gymnastics</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="header-background">
        <div className="header-top">
          <Link
            className="header-logo"
            href="/">
            Velocity Gymnastics
          </Link>
          <Link
            className="header-enroll"
            href="/enroll">
            Enroll Now
          </Link>
        </div>

        <div className="header-pages">
          {displayPages(props.current)}

          <div className="header-socials">
            <a href="https://www.facebook.com" target="blank">
              <FontAwesomeIcon icon={faFacebook} /> </a>
            <a href="https://www.instagram.com" target="blank">
              <FontAwesomeIcon icon={faInstagram} /> </a>
            <a href="https://www.youtube.com" target="blank">
              <FontAwesomeIcon icon={faYoutube} /> </a>
            <a href="https://www.twitter.com" target="blank">
              <FontAwesomeIcon icon={faTwitter} /> </a>
          </div>
        </div>

        <div className="header-bottom">
        </div>
      </div>
    </>
  );
};
export default Header;

