import React from 'react';
import PageButtons from "./PageButtons"
import Head from "next/head"
import Link from 'next/link';

interface pagesType {
  [key: string]: {
    pagePath: string,
    style: string,
  }
}
const pages: pagesType = {
  "Gallery": { pagePath: "/gallery", style: "" },
  "Coaches": { pagePath: "/coaches", style: "" },
  "Schedules": { pagePath: "/schedule", style: "" },
  "Classes": { pagePath: "/classes", style: "" },
  "About": { pagePath: "/about", style: "" },
}

const selectPage = (selected: string) => {
  for (const page in pages) { pages[page].style = "" }
  if (selected)
    pages[selected].style = "bg-orange-400 pointer-events-none"
}

const displayPages = () => {
  return Object.keys(pages).map((page, index) => {
    const style = pages[page]?.style
    return  (
      <PageButtons 
        key={index} 
        pagePath={pages[page]?.pagePath} 
        label={page} 
        style={style} 
        select={selectPage}
      />
    )
  })
}

const Header: React.FC = () => {
  return (
    <>
      <Head>
        <title>Velocity Gymnastics</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="header-background">
        <div className="header-top">
          <Link 
            className="header-logo" 
            href="/"
            onClick={() => {selectPage("")}}>
            Velocity Gymnastics
          </Link>
          <Link 
            className="header-enroll" 
            href="/enroll"
            onClick={() => {selectPage("")}}>
            Enroll Now
          </Link>
        </div>

        <div className="header-pages">
          {displayPages()}
          <div className="header-socials">
            <div className="social"> FB </div>
            <div className="social"> IG </div>
            <div className="social"> YT </div>
          </div>
        </div>

        <div className="header-bottom">
        </div>
      </div>
    </>
  );
};
export default Header;

